/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pokemon;

/**
 *
 * @author Kevin Sosa
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_atacar1 = new javax.swing.JButton();
        btn_atacar2 = new javax.swing.JButton();
        pb_vida1 = new javax.swing.JProgressBar();
        pb_vida2 = new javax.swing.JProgressBar();
        curar1 = new javax.swing.JButton();
        curar2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        kevin = new javax.swing.JLabel();
        REINICIAR = new javax.swing.JButton();
        SALIR = new javax.swing.JButton();
        turno1 = new javax.swing.JButton();
        turno2 = new javax.swing.JButton();
        ata1 = new javax.swing.JButton();
        ata2 = new javax.swing.JButton();
        ata3 = new javax.swing.JButton();
        ata4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAutoRequestFocus(false);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokemon/images (1).jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 170, 200));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokemon/BBB.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, 160, 200));

        btn_atacar1.setText("Atacar");
        btn_atacar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_atacar1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_atacar1MousePressed(evt);
            }
        });
        btn_atacar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atacar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_atacar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        btn_atacar2.setText("Atacar");
        btn_atacar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_atacar2MousePressed(evt);
            }
        });
        btn_atacar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atacar2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_atacar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 260, -1, -1));

        pb_vida1.setValue(100);
        getContentPane().add(pb_vida1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        pb_vida2.setValue(100);
        getContentPane().add(pb_vida2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, -1, -1));

        curar1.setText("Curar");
        curar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                curar1MouseClicked(evt);
            }
        });
        curar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                curar1ActionPerformed(evt);
            }
        });
        getContentPane().add(curar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, -1, -1));

        curar2.setText("Curar");
        curar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                curar2MouseClicked(evt);
            }
        });
        curar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                curar2ActionPerformed(evt);
            }
        });
        getContentPane().add(curar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, -1, -1));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 312, -1, -1));

        kevin.setBackground(new java.awt.Color(0, 0, 0));
        kevin.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        kevin.setForeground(new java.awt.Color(255, 255, 255));
        kevin.setText("jLabel4");
        getContentPane().add(kevin, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 220, 30));

        REINICIAR.setText("REINICIAR");
        REINICIAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                REINICIARMouseClicked(evt);
            }
        });
        REINICIAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REINICIARActionPerformed(evt);
            }
        });
        getContentPane().add(REINICIAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, -1, -1));

        SALIR.setText("SALIR");
        SALIR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SALIRMouseClicked(evt);
            }
        });
        getContentPane().add(SALIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, -1, -1));

        turno1.setText("TURNO1");
        turno1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                turno1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                turno1MousePressed(evt);
            }
        });
        turno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turno1ActionPerformed(evt);
            }
        });
        getContentPane().add(turno1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        turno2.setText("TURNO2");
        turno2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                turno2MousePressed(evt);
            }
        });
        turno2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turno2ActionPerformed(evt);
            }
        });
        getContentPane().add(turno2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 350, -1, -1));

        ata1.setText("ATAQUE ESPECIAL1");
        ata1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ata1MouseClicked(evt);
            }
        });
        ata1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ata1ActionPerformed(evt);
            }
        });
        getContentPane().add(ata1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 140, -1));

        ata2.setText("ATAQUE ESPECIAL2");
        ata2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ata2MouseClicked(evt);
            }
        });
        ata2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ata2ActionPerformed(evt);
            }
        });
        getContentPane().add(ata2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 140, -1));

        ata3.setText("ATAQUE ESPECIA1");
        ata3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ata3MouseClicked(evt);
            }
        });
        ata3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ata3ActionPerformed(evt);
            }
        });
        getContentPane().add(ata3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, 150, -1));

        ata4.setText("ATAQUE ESPECIAL2");
        ata4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ata4MouseClicked(evt);
            }
        });
        ata4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ata4ActionPerformed(evt);
            }
        });
        getContentPane().add(ata4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, 150, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokemon/lugia-pokemo.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, -2, 730, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_atacar1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_atacar1MousePressed
        
    }//GEN-LAST:event_btn_atacar1MousePressed

    private void btn_atacar2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_atacar2MousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btn_atacar2MousePressed

    private void btn_atacar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atacar2ActionPerformed
 int vida1 = pb_vida1.getValue();
        vida1-=5;
        pb_vida1.setValue(vida1);  
        btn_atacar2.setEnabled(false);
        curar2.setEnabled(false);
        ata3.setEnabled(false);
        ata4.setEnabled(false);
        turno2.setEnabled(false);
        turno1.setEnabled(true);
             if (vida1 <=0){
            kevin.setText("Jugador 2 ganador ");
             }// TODO add your handling code here:
    }//GEN-LAST:event_btn_atacar2ActionPerformed

    private void curar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_curar1ActionPerformed
    int vida1 = pb_vida1.getValue();
    vida1+=60;
        pb_vida1.setValue(vida1);  
        btn_atacar1.setEnabled(false);
        curar1.setEnabled(false);
        ata1.setEnabled(false);
        ata2.setEnabled(false);
        turno1.setEnabled(false);
        turno2.setEnabled(true);
            System.out.println(Math.random()*1000%10);
    }//GEN-LAST:event_curar1ActionPerformed

    private void curar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_curar1MouseClicked
        
    }//GEN-LAST:event_curar1MouseClicked

    private void curar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_curar2MouseClicked

    }//GEN-LAST:event_curar2MouseClicked

    private void btn_atacar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atacar1ActionPerformed
 int vida2 = pb_vida2.getValue();
        vida2-=5;
        pb_vida2.setValue(vida2);
        btn_atacar1.setEnabled(false);
        curar1.setEnabled(false);
        ata1.setEnabled(false);
        ata2.setEnabled(false);
        turno1.setEnabled(false);
        turno2.setEnabled(true);
             if (vida2 <=0){
            kevin.setText("Jugador 1 ganador ");
            btn_atacar1.setEnabled(false);
             }        
    }//GEN-LAST:event_btn_atacar1ActionPerformed

    private void btn_atacar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_atacar1MouseClicked

    }//GEN-LAST:event_btn_atacar1MouseClicked

    private void REINICIARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_REINICIARMouseClicked

    }//GEN-LAST:event_REINICIARMouseClicked

    private void SALIRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SALIRMouseClicked
System.exit(0);

        // TODO add your handling code here:
    }//GEN-LAST:event_SALIRMouseClicked

    private void turno1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_turno1MouseClicked
String turno = turno1.getText();
String turn = turno2.getText();
String vida1 =  btn_atacar1.getText();
String vida2 =  btn_atacar2.getText();
    }//GEN-LAST:event_turno1MouseClicked

    private void turno1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_turno1MousePressed
    
    }//GEN-LAST:event_turno1MousePressed

    private void turno2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_turno2MousePressed
    
    }//GEN-LAST:event_turno2MousePressed

    private void ata1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ata1ActionPerformed
  int vida2 = pb_vida2.getValue();
        vida2-=20;
        pb_vida2.setValue(vida2);
         btn_atacar1.setEnabled(false);
        curar1.setEnabled(false);
        ata1.setEnabled(false);
        ata2.setEnabled(false);
        turno1.setEnabled(false);
        turno2.setEnabled(true);
        System.out.println(Math.random()*2000%100);
             if (vida2 <=0){
            kevin.setText("Jugador 1 ganador ");
             }       
    }//GEN-LAST:event_ata1ActionPerformed

    private void ata1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ata1MouseClicked

    }//GEN-LAST:event_ata1MouseClicked

    private void ata2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ata2MouseClicked

    }//GEN-LAST:event_ata2MouseClicked

    private void ata3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ata3MouseClicked
          
    }//GEN-LAST:event_ata3MouseClicked

    private void ata4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ata4MouseClicked
             
    }//GEN-LAST:event_ata4MouseClicked

    private void REINICIARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REINICIARActionPerformed
int vida1 = pb_vida1.getValue();
vida1 = 100;
pb_vida1.setValue(vida1);

int vida2 = pb_vida2.getValue();
vida2= 100;
pb_vida2.setValue(vida2);

String nuevo = kevin.getText();
nuevo = "nueva partida";

 btn_atacar1.setEnabled(true);
 curar1.setEnabled(true);
 ata1.setEnabled(true);
 ata2.setEnabled(true);
 turno1.setEnabled(true);

kevin.setText(nuevo);
btn_atacar2.setEnabled(true);
curar2.setEnabled(true);
ata3.setEnabled(true);
ata4.setEnabled(true);
turno2.setEnabled(true);       
    }//GEN-LAST:event_REINICIARActionPerformed

    private void curar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_curar2ActionPerformed
int vida2 = pb_vida2.getValue();
        vida2+=30;
        pb_vida2.setValue(vida2);
        btn_atacar2.setEnabled(false);
        curar2.setEnabled(false);
        ata3.setEnabled(false);
        ata4.setEnabled(false);
        turno2.setEnabled(false);
        turno1.setEnabled(true);
         
       System.out.println(Math.random()*1000%10);        
    }//GEN-LAST:event_curar2ActionPerformed

    private void turno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turno1ActionPerformed
    btn_atacar2.setEnabled(false);
    btn_atacar1.setEnabled(true);
    curar2.setEnabled(false);
    ata3.setEnabled(false);
    ata4.setEnabled(false);
    ata2.setEnabled(true);
    turno2.setEnabled(false);
    ata1.setEnabled(true);
    curar1.setEnabled(true);
    }//GEN-LAST:event_turno1ActionPerformed

    private void ata4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ata4ActionPerformed
   int vida1 = pb_vida2.getValue();
        vida1-=50;
        pb_vida1.setValue(vida1);
         btn_atacar2.setEnabled(false);
        curar2.setEnabled(false);
        ata3.setEnabled(false);
        ata4.setEnabled(false);
        turno2.setEnabled(false);
        turno1.setEnabled(true);
        System.out.println(Math.random()*10000%100);
             if (vida1 <=0)
            kevin.setText("Jugador 1 ganador ");        
    }//GEN-LAST:event_ata4ActionPerformed

    private void ata3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ata3ActionPerformed
     int vida1 = pb_vida1.getValue();
        vida1-=60;
        pb_vida1.setValue(vida1);
        btn_atacar2.setEnabled(false);
        curar2.setEnabled(false);
        ata3.setEnabled(false);
        ata4.setEnabled(false);
        turno2.setEnabled(false);
        turno1.setEnabled(true);
        System.out.println(Math.random()*20%5);
             if (vida1 <=0)
            kevin.setText("Jugador 1 ganador ");
    }//GEN-LAST:event_ata3ActionPerformed

    private void ata2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ata2ActionPerformed
       int vida2 = pb_vida2.getValue();
        vida2-=60;
        pb_vida2.setValue(vida2);
        btn_atacar1.setEnabled(false);
        curar1.setEnabled(false);
        ata1.setEnabled(false);
        ata2.setEnabled(false);
        turno1.setEnabled(false);
        turno2.setEnabled(true);
        System.out.println(Math.random()*200%4);
             if (vida2 <=0){
            kevin.setText("Jugador 1 ganador ");
             }
    }//GEN-LAST:event_ata2ActionPerformed

    private void turno2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turno2ActionPerformed
  btn_atacar1.setEnabled(false);
    btn_atacar2.setEnabled(true);
    curar1.setEnabled(false);
    curar2.setEnabled(true);
    ata1.setEnabled(false);
    ata2.setEnabled(false);
    ata3.setEnabled(true);
    ata4.setEnabled(true);
    turno1.setEnabled(false);
    }//GEN-LAST:event_turno2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new NewJFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton REINICIAR;
    private javax.swing.JButton SALIR;
    private javax.swing.JButton ata1;
    private javax.swing.JButton ata2;
    private javax.swing.JButton ata3;
    private javax.swing.JButton ata4;
    private javax.swing.JButton btn_atacar1;
    private javax.swing.JButton btn_atacar2;
    private javax.swing.JButton curar1;
    private javax.swing.JButton curar2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel kevin;
    private javax.swing.JProgressBar pb_vida1;
    private javax.swing.JProgressBar pb_vida2;
    private javax.swing.JButton turno1;
    private javax.swing.JButton turno2;
    // End of variables declaration//GEN-END:variables
}
